
before_script:
  - curl -LO https://releases.rancher.com/cli/v0.6.2/rancher-linux-amd64-v0.6.2.tar.gz
  - tar zxf rancher-linux-amd64-v0.6.2.tar.gz

build_test:
  script:
    - docker build -t dockerimages.fhcrc.org/scicomp-dashboard:latest .
    - |
        if docker ps -a|tr -s ' '|rev|cut -d ' ' -f 1|rev|grep -q scicomp-dashboard
        then
          docker stop scicomp-dashboard && docker rm --force scicomp-dashboard
        fi
    - docker run --rm -w /scicomp-dashboard $DOCKER_HUB_HOST/$DOCKER_USER/scicomp-dashboard:$CIRCLE_SHA1 python3 unit_tests.py


deploy:
  only:
    refs:
        - master
  script:
    - docker login --username $DOCKERIMAGES_USER --password $DOCKERIMAGES_PASS https://dockerimages.fhcrc.org
    - docker push dockerimages.fhcrc.org/scicomp-dashboard:latest
    - sleep 15
    - rancher-v0.6.2/rancher --url https://ponderosa.fhcrc.org --access-key $RANCHERAPI_KEY --secret-key $RANCHERAPI_SECRET up -d --pull --force-upgrade --confirm-upgrade --stack scicomp-dashboard --file docker-compose.yml --rancher-file rancher-compose.yml
